- name: Install Grafana & Jenkins with Docker
  hosts: servers
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present
    
    - name: Pull Jenkins Docker image
      command: docker pull jenkins/jenkins

    - name: Start Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        restart_policy: always
        ports:
          - "8080:8080"    